spring:
  application:
    name: oper-sys
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    #JDBC 配置
    url: jdbc:oracle:thin:@192.168.2.216:1521:GTSSDB
    username: utgtss2
    password: zjjygtss2
    driver-class-name: oracle.jdbc.driver.OracleDriver
    #druid:      #https://github.com/alibaba/druid/blob/master/druid-spring-boot-starter/src/test/resources/application.properties
    #连接池配置
    initial-size: 1
    max-active: 20
    min-idle: 1
    max-wait: 60000
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    # max-open-prepared-statements: #和上面的等价
    validation-query: SELECT 'x' from dual
    #validation-query-timeout:
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    #max-evictable-idle-time-millis:
    #filters: #配置多个英文逗号分隔
  redis:
    hostName: 192.168.2.225
    port: 6379
    password: redis12345
    database: 2
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0

  cloud:
    stream:
      bindings:
        input:
          destination: queue.log.messages
          binder: local_rabbit
          group: logMessageConsumers
        test_input:
          destination: queue.log.messages1
          binder: local_rabbit
          group: logMessageConsumers1
        output:
          destination: queue.pretty.log.messages
          binder: local_rabbit
        test_output:
          destination: queue.log.messages1
          binder: local_rabbit
          group: logMessageConsumers1
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.2.217
                port: 5672
                username: longf
                password: siiCfl8801
                virtual-host: /


mybatis:
  basepackage: com.sctoc.microserver.oper.sys.mapper
  #xmlLocation: classpath:mapper/**/*.xml
  mapper-locations: "classpath*:mapper/*.xml"

server:
  port: ${microserver.oper-auth.port:8940} #启动端口
  tomcat:
    min-spare-threads: 20
    max-threads: 200
logging:
  level:
    org.hibernate.SQL: debug

eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    healthcheck:
      enabled: true


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml


